events {}

http {
    upstream restaurant_upstream {
        server restaurant-service-1:3001;
        server restaurant-service-2:3005;
    }

    upstream menu_upstream {
        server menu-service-1:3002;
        server menu-service-2:3006;
    }

    upstream order_upstream {
        server order-service-1:3003;
        server order-service-2:3007;
    }

    server {
        listen 80;

        location /restaurants {
            proxy_pass http://restaurant_upstream;
        }

        location /menu {
            proxy_pass http://menu_upstream;
        }

        location /orders {
            proxy_pass http://order_upstream;
        }
    }
}